### ISSUE TITLE
Error in Instantiating

### ISSUE THREAD

**Issue by Loevion** [BMecke/hantekosc#1]
if I execute the following code:
`from hantekosc import oscilloscope
osc = oscilloscope.Oscilloscope()
`
I get this error: 

/home/user/.venv/bin/python /home/user/exaple py.py 
building C code
Traceback (most recent call last):
  File "/home/user/.venv/lib/python3.12/site-packages/hantekosc/c_code/c_code.py", line 39, in __init__
    from _triggering.lib import find_trigger_position, create_timing_data, create_pretrigger_timing_data, \
ModuleNotFoundError: No module named '_triggering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.venv/lib/python3.12/site-packages/cffi/_shimmed_dist_utils.py", line 12, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/exaple py.py", line 2, in <module>
    osc = oscilloscope.Oscilloscope()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/lib/python3.12/site-packages/hantekosc/oscilloscope.py", line 34, in __init__
    self.c_code = C_Code()
                  ^^^^^^^^
  File "/home/user/.venv/lib/python3.12/site-packages/hantekosc/c_code/c_code.py", line 48, in __init__
    self.ffibuilder.compile(c_code_path, verbose=False)
  File "/home/user/.venv/lib/python3.12/site-packages/cffi/api.py", line 727, in compile
    return recompile(self, module_name, source, tmpdir=tmpdir,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/lib/python3.12/site-packages/cffi/recompiler.py", line 1561, in recompile
    ext = ffiplatform.get_extension(ext_c_file, module_name, **kwds)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.venv/lib/python3.12/site-packages/cffi/ffiplatform.py", line 9, in get_extension
    from cffi._shimmed_dist_utils import Extension
  File "/home/user/.venv/lib/python3.12/site-packages/cffi/_shimmed_dist_utils.py", line 16, in <module>
    raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
Exception: This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.

Whats the problem ?
thanks loevion

**Comment by BMecke** [comment]
Hello Loevion, 
it seems that there was an error during the installation of setuptools. Can you try installing setuptools manually and let me know if it works?
You can use this command: `pip install setuptools`
